services:
  pygeoapi:
    build: .
    command: ["run-with-hot-reload"]
    container_name: global-geoconnex-us
    ports:
      - 5000:80
    volumes:
      - ./pygeoapi.config.yml:/pygeoapi/local.config.yml
    env_file:
      - .env
    depends_on:
      - database

  database:
    container_name: database
    image: postgis/postgis:18-3.6-alpine
    platform: linux/amd64
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  hydrodump:
    container_name: hydrodump
    image: ghcr.io/cgs-earth/hydrodump-action:latest
    volumes:
      - ./data:/data
    command: ["hydrodump", "run"]
    env_file:
      - .env

volumes:
  db_data: