data_link: &data_link
  type: text/html
  rel: canonical
  title: Data source
  hreflang: en-US

provider_defaults: &provider_defaults
  type: feature
  name: PostgreSQL
  data:
    host: ${POSTGRES_HOST}
    dbname: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  id_field: id
  title_field: name
  uri_field: uri
  geom_field: geom

tile_defaults: &tile_defaults
  <<: *provider_defaults
  type: tile
  name: MVT-PostgresCache
  mvt_table: mvt_tiles
  storage_crs: http://www.opengis.net/def/crs/EPSG/0/4326
  disable_cache_at_z: 8
  options:
    zoom:
      min: 1
      max: 16
  format:
    name: pbf
    mimetype: application/vnd.mapbox-vector-tile

server:
  bind:
    host: localhost #change to your hostname if running your own instance
    port: 5000
  url: ${PYGEOAPI_URL} #change to host URL  if running your own instance
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: true
  language: en-US
  cors: true
  pretty_print: true
  limits:
    default_items: 500
    max_items: 10000
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'

logging:
  level: ${PYGEOAPI_LOGLEVEL:-ERROR}
  # logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title: Geoconnex Reference Service
    description: Provides reference for community features in geoconnex.us
    keywords:
      - Geospatial
      - Geoconnex
      - Reference
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://github.com/internetofwater/reference.geoconnex.us
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Center for Geospatial Solutions
    url: https://cgsearth.org/
  contact:
    address: 113 Brattle St
    city: Cambridge
    stateorprovince: Massachussetts
    postalcode: 02138
    country: USA
    email: internetofwater@lincolninst.edu
    url: https://internetofwater.org
    role: pointOfContact
    name: Benjamin Webb

resources:
  hydrobasins:
    type: collection
    title: Hydrobasins
    description: Level06 Hydrologic Basins from Hydrosheds
    keywords:
      - Hydrologic Basins
      - lev06
    links:
      - <<: *data_link
        href: https://www.hydrosheds.org/products/hydrobasins
        title: HydroBASINS v1.0 Documentation
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: null
        end: null
    providers:
      - <<: *provider_defaults
        id_field: id
        table: hydrobasins_lvl6_context
      - <<: *tile_defaults
        id_field: id
        table: hydrobasins_lvl6_context

  resources:
    hydrobasins:
      type: collection
      title: Hydrobasins
      description: Level05 Hydrologic Basins from Hydrosheds
      keywords:
        - Hydrologic Basins
        - lev05
      links:
        - <<: *data_link
          href: https://www.hydrosheds.org/products/hydrobasins
          title: HydroBASINS v1.0 Documentation
      extents:
        spatial:
          bbox: [-180, -90, 180, 90]
          crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
        temporal:
          begin: null
          end: null
      providers:
        - <<: *provider_defaults
          id_field: id
          table: hydrobasins_lvl5_context
        - <<: *tile_defaults
          id_field: id
          table: hydrobasins_lvl5_context

  flowlines:
    type: collection
    title: Flowlines
    description: Merit Hydrologic Flowlines
    keywords:
      - Hydrologic Flowlines
      - Merit
    links:
      - <<: *data_link
        href: https://water.usgs.gov/themes/hydrologic-units/
        title: Hydrologic Unit Documentation
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: null
        end: null
    providers:
      - <<: *provider_defaults
        id_field: comid
        table: merit_plus
        geom: wkb_geometry
        count: false
      - <<: *tile_defaults
        id_field: comid
        table: merit_plus
        geom: wkb_geometry
