data_link: &data_link
  type: text/html
  rel: canonical
  hreflang: en-US
  href: https://water.usgs.gov/themes/hydrologic-units/
  title: Hydrologic Unit Documentation

provider_defaults: &provider_defaults
  type: feature
  name: PostgreSQL
  data:
    host: ${POSTGRES_HOST}
    dbname: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  id_field: id
  title_field: name
  uri_field: uri
  geom_field: geom

tile_defaults: &tile_defaults
  <<: *provider_defaults
  type: tile
  name: pygeoapi_plugins.provider.mvt_postgresql.MVTPostgreSQLProvider_
  mvt_table: mvt_tiles
  storage_crs: http://www.opengis.net/def/crs/EPSG/0/4326
  disable_cache_at_z: 8
  min_pixel: 256
  simplify_geometry: true
  options:
    zoom:
      min: 0
      max: 16
  format:
    name: pbf
    mimetype: application/vnd.mapbox-vector-tile

server:
  bind:
    host: localhost #change to your hostname if running your own instance
    port: 5000
  url: ${PYGEOAPI_URL} #change to host URL  if running your own instance
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: true
  language: en-US
  cors: true
  pretty_print: true
  limits:
    default_items: 500
    max_items: 10000
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'

logging:
  level: ${PYGEOAPI_LOGLEVEL:-ERROR}
  # logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title: Geoconnex Reference Service
    description: Provides reference for community features in geoconnex.us
    keywords:
      - Geospatial
      - Geoconnex
      - Reference
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://github.com/internetofwater/reference.geoconnex.us
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Center for Geospatial Solutions
    url: https://cgsearth.org/
  contact:
    address: 113 Brattle St
    city: Cambridge
    stateorprovince: Massachussetts
    postalcode: 02138
    country: USA
    email: internetofwater@lincolninst.edu
    url: https://internetofwater.org
    role: pointOfContact
    name: Benjamin Webb

resources:
  hydrobasins/lvl1:
    type: collection
    title: One-digit Hydrobasins
    description: One-digit Hydrobasins
    keywords:
      - Hydrologic Basins
      - HU01
    links: [*data_link]
    extents: &world-extent
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    providers:
      - <<: *provider_defaults
        table: hydrobasins_lvl1_context
      - <<: *tile_defaults
        table: hydrobasins_lvl1_context

  hydrobasins/lvl2:
    type: collection
    title:  Two-digit Hydrobasins
    description: Two-digit Hydrobasins
    keywords:
      - Hydrologic Basins
      - HU02
    links: [*data_link] 
    extents: *world-extent
    providers:
      - <<: *provider_defaults
        table: hydrobasins_lvl2_context
      - <<: *tile_defaults
        table: hydrobasins_lvl2_context
  hydrobasins/lvl3:
    type: collection
    title: Three-digit Hydrobasins
    description: Three-digit Hydrobasins
    keywords:
      - Hydrologic Basins
      - HU03
    links: [*data_link]
    extents: *world-extent
    providers:
      - <<: *provider_defaults
        table: hydrobasins_lvl3_context
      - <<: *tile_defaults
        table: hydrobasins_lvl3_context
  hydrobasins/lvl4:
    type: collection
    title: Four-digit Hydrobasins
    description: Four-digit Hydrobasins
    keywords:
      - Hydrologic Basins
      - HU04
    links: [*data_link]
    extents: *world-extent
    providers:
      - <<: *provider_defaults
        table: hydrobasins_lvl4_context
      - <<: *tile_defaults
        table: hydrobasins_lvl4_context

  hydrobasins/lvl5:
    type: collection
    title: Five-digit Hydrobasins
    description: Five-digit Hydrobasins
    keywords:
      - Hydrologic Basins
      - HU05
    links: [*data_link]
    extents: *world-extent
    providers:
      - <<: *provider_defaults
        table: hydrobasins_lvl5_context
      - <<: *tile_defaults
        table: hydrobasins_lvl5_context

  hydrobasins/lvl6:
    type: collection
    title: Six-digit Hydrobasins
    description: Six-digit Hydrobasins
    keywords:
      - Hydrologic Basins
      - HU04
    links: [*data_link]
    extents: *world-extent
    providers:
      - <<: *provider_defaults
        table: hydrobasins_lvl6_context
      - <<: *tile_defaults
        table: hydrobasins_lvl6_context

  hydrobasins/lvl7:
    type: collection
    title: Seven-digit Hydrobasins
    description: Seven-digit Hydrobasins
    keywords:
      - Hydrologic Basins
      - HU07
    links: [*data_link]
    extents: *world-extent
    providers:
      - <<: *provider_defaults
        table: hydrobasins_lvl7_context
      - <<: *tile_defaults
        table: hydrobasins_lvl7_context
        min_pixel: 512

  hydrobasins/lvl8:
    type: collection
    title: Eight-digit Hydrobasins
    description: Eight-digit Hydrobasins
    keywords:
      - Hydrologic Basins
      - HU08
    links: [*data_link]
    extents: *world-extent
    providers:
      - <<: *provider_defaults
        table: hydrobasins_lvl8_context
      - <<: *tile_defaults
        table: hydrobasins_lvl8_context
        min_pixel: 512

  hydrobasins/lvl9:
    type: collection
    title: Nine-digit Hydrobasins
    description: Nine-digit Hydrobasins
    keywords:
      - Hydrologic Basins
      - HU09
    links: [*data_link]
    extents: *world-extent
    providers:
      - <<: *provider_defaults
        table: hydrobasins_lvl9_context
      - <<: *tile_defaults
        table: hydrobasins_lvl9_context
        min_pixel: 512

  hydrobasins/lvl10:
    type: collection
    title: Ten-digit Hydrobasins
    description: Ten-digit Hydrobasins
    keywords:
      - Hydrologic Basins
      - HU10
    links: [*data_link]
    extents: *world-extent
    providers:
      - <<: *provider_defaults
        table: hydrobasins_lvl10_context
      - <<: *tile_defaults
        table: hydrobasins_lvl10_context
        min_pixel: 512

  hydrobasins/lvl11:
    type: collection
    title: Eleven-digit Hydrobasins
    description: Eleven-digit Hydrobasins
    keywords:
      - Hydrologic Basins
      - HU11
    links: [*data_link]
    extents: *world-extent
    providers:
      - <<: *provider_defaults
        table: hydrobasins_lvl11_context
      - <<: *tile_defaults
        table: hydrobasins_lvl11_context
        min_pixel: 512

  hydrobasins/lvl12:
    type: collection
    title: Twelve-digit Hydrobasins
    description: Twelve-digit Hydrobasins
    keywords:
      - Hydrologic Basins
      - HU12
    links: [*data_link]
    extents: *world-extent
    providers:
      - <<: *provider_defaults
        table: hydrobasins_lvl12_context
      - <<: *tile_defaults
        table: hydrobasins_lvl12_context
        min_pixel: 512

  flowlines:
    type: collection
    title: Flowlines
    description: Merit Hydrologic Flowlines
    keywords:
      - Hydrologic Flowlines
      - Merit
    links:
      - <<: *data_link
        href: https://water.usgs.gov/themes/hydrologic-units/
        title: Hydrologic Unit Documentation
    extents: *world-extent
    providers:
      - <<: *provider_defaults
        id_field: comid
        table: merit_plus
        geom: wkb_geometry
        count: false
      - <<: *tile_defaults
        id_field: comid
        table: merit_plus
        geom: wkb_geometry
        min_pixel: 1024
